### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by henryborchers** [devpi/devpi-jenkins#9]
It'd be a shame because I really love the idea of this project and could use it.

**Comment by fschulze** [comment]
Yes and no. I'm not sure it still works with current Jenkins. I don't know if anyone still uses it. The main obstacle for improvements is the required hook into/from devpi-server. There are plans for a better event system in devpi-server which would allow much better integration, but there is no hard ETA for it. I hope for Q1 2020.

**Comment by henryborchers** [comment]
I completely understand. It just that I absolutely love your project. It's helped me so much to organize all my projects. 

One of the killer features for me is the integrated test results with the metadata. It give me more confidence that a python package is ready to be released to a production index. I just can't wait to better automate this data collection.

I'm looking forward to Q1 2020. :)
